app = "metro-backend-example"
primary_region = "ams"

[build]
  dockerfile = "infra/docker/backend.Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    grace_period = "10s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    timeout = "3s"

