// Auto-generated by tools/extract-stations.mjs
export const stationPositions: Record<string, { cx: number; cy: number; labelX: number; labelY: number }> = {
  "RB": {
    "cx": 47,
    "cy": 136,
    "labelX": 6,
    "labelY": 122.5
  },
  "AS": {
    "cx": 85,
    "cy": 136,
    "labelX": 44.4219,
    "labelY": 158.5
  },
  "AF": {
    "cx": 123,
    "cy": 136,
    "labelX": 94.2656,
    "labelY": 121.5
  },
  "PO": {
    "cx": 161,
    "cy": 136,
    "labelX": 172.457,
    "labelY": 138.5
  },
  "CA": {
    "cx": 193,
    "cy": 168,
    "labelX": 205,
    "labelY": 170.5
  },
  "CM": {
    "cx": 225,
    "cy": 200,
    "labelX": 237,
    "labelY": 202.5
  },
  "AH": {
    "cx": 257,
    "cy": 232,
    "labelX": 269,
    "labelY": 234.5
  },
  "LA": {
    "cx": 289,
    "cy": 264,
    "labelX": 301,
    "labelY": 266.5
  },
  "JZ": {
    "cx": 321,
    "cy": 296,
    "labelX": 333,
    "labelY": 297.5
  },
  "PE": {
    "cx": 353,
    "cy": 328,
    "labelX": 238.52,
    "labelY": 332.5
  },
  "SS": {
    "cx": 385,
    "cy": 361,
    "labelX": 303.824,
    "labelY": 365.5
  },
  "PA": {
    "cx": 426,
    "cy": 401,
    "labelX": 373.629,
    "labelY": 405.5
  },
  "MP": {
    "cx": 462,
    "cy": 437,
    "labelX": 337.16,
    "labelY": 442.5
  },
  "AV": {
    "cx": 498,
    "cy": 473,
    "labelX": 495,
    "labelY": 459.5
  },
  "RE": {
    "cx": 529,
    "cy": 504,
    "labelX": 433.48,
    "labelY": 509.5
  },
  "BC": {
    "cx": 562,
    "cy": 536,
    "labelX": 571,
    "labelY": 536.5
  },
  "TP": {
    "cx": 635,
    "cy": 553,
    "labelX": 590,
    "labelY": 575.5
  },
  "SP": {
    "cx": 693,
    "cy": 553,
    "labelX": 705,
    "labelY": 555.5
  },
  "AP": {
    "cx": 636,
    "cy": 115,
    "labelX": 566.109,
    "labelY": 118.5
  },
  "EN": {
    "cx": 684,
    "cy": 115,
    "labelX": 649.174,
    "labelY": 137.5
  },
  "MO": {
    "cx": 732,
    "cy": 114,
    "labelX": 702,
    "labelY": 100.5
  },
  "OR": {
    "cx": 754,
    "cy": 162,
    "labelX": 699.93,
    "labelY": 165.5
  },
  "CR": {
    "cx": 736,
    "cy": 222,
    "labelX": 660,
    "labelY": 224.5
  },
  "OS": {
    "cx": 704,
    "cy": 254,
    "labelX": 716,
    "labelY": 259.5
  },
  "CH": {
    "cx": 672,
    "cy": 286,
    "labelX": 684,
    "labelY": 291.5
  },
  "BV": {
    "cx": 640,
    "cy": 318,
    "labelX": 652,
    "labelY": 323.5
  },
  "OL": {
    "cx": 608,
    "cy": 352,
    "labelX": 620,
    "labelY": 356.5
  },
  "RA": {
    "cx": 452,
    "cy": 479,
    "labelX": 412.648,
    "labelY": 483.5
  },
  "PI": {
    "cx": 462,
    "cy": 399,
    "labelX": 474,
    "labelY": 402.5
  },
  "SA": {
    "cx": 462,
    "cy": 361,
    "labelX": 470,
    "labelY": 352.5
  },
  "CP": {
    "cx": 462,
    "cy": 322,
    "labelX": 474,
    "labelY": 319.5
  },
  "EC": {
    "cx": 462,
    "cy": 274,
    "labelX": 474,
    "labelY": 277.5
  },
  "CU": {
    "cx": 462,
    "cy": 226,
    "labelX": 474,
    "labelY": 224.5
  },
  "QC": {
    "cx": 462,
    "cy": 146,
    "labelX": 338,
    "labelY": 149.5
  },
  "LU": {
    "cx": 462,
    "cy": 114,
    "labelX": 411,
    "labelY": 117.5
  },
  "AX": {
    "cx": 462,
    "cy": 82,
    "labelX": 388,
    "labelY": 86.5
  },
  "SR": {
    "cx": 462,
    "cy": 50,
    "labelX": 357,
    "labelY": 54.5
  },
  "OD": {
    "cx": 462,
    "cy": 18,
    "labelX": 402,
    "labelY": 22.5
  },
  "CS": {
    "cx": 493,
    "cy": 558,
    "labelX": 403.07,
    "labelY": 561.5
  },
  "RO": {
    "cx": 562,
    "cy": 503,
    "labelX": 574,
    "labelY": 506.5
  },
  "MM": {
    "cx": 562,
    "cy": 475,
    "labelX": 574,
    "labelY": 479.5
  },
  "IN": {
    "cx": 562,
    "cy": 447,
    "labelX": 574,
    "labelY": 450.5
  },
  "AN": {
    "cx": 562,
    "cy": 419,
    "labelX": 574,
    "labelY": 423.5
  },
  "AR": {
    "cx": 562,
    "cy": 390,
    "labelX": 574,
    "labelY": 393.5
  },
  "AM": {
    "cx": 562,
    "cy": 361,
    "labelX": 504,
    "labelY": 377.5
  },
  "AE": {
    "cx": 562,
    "cy": 313,
    "labelX": 574,
    "labelY": 316.5
  },
  "RM": {
    "cx": 562,
    "cy": 265,
    "labelX": 574,
    "labelY": 268.5
  },
  "AL": {
    "cx": 562,
    "cy": 217,
    "labelX": 574,
    "labelY": 221.5
  },
  "CG": {
    "cx": 462,
    "cy": 178,
    "labelX": 471,
    "labelY": 168.5
  },
  "TE": {
    "cx": 414,
    "cy": 178,
    "labelX": 353,
    "labelY": 181.5
  }
};
